services:
- postgresql
before_script:
- bundle install
- psql -c 'create database pgapp_test;' -U postgres
- bin/rails db:migrate
dist: trusty
language: ruby
rvm:
- 2.6.5
script:
- bundle exec rubocop
- bundle exec rspec
deploy:
  provider: heroku
  api_key:
    secure: LNGZdY2Pwlwsco9blGyBIynBKRI7OHYKAXH/h8sHdqZ8yi82RHyotg9FquQJOK30nLkObRknfMOsnWNzjCCPgkaWKhflbh5uNAz5ngsVEPZRYGkWYayLu9iWDi1iOLE2j61NYNtb3rPxkClryA+JbwknLIKTc7Vu9KI2lVcbEBEZfFTy4eY20PUvPQUq/VU9R/KyCbHSur/DIvTaOR1iBDucPIRD5Fbx0GV4Pqt/VPd1cGJ7gUHwWs9pPMJ5ZrR7LNuWZKuJCfToW1W6PA26xNIRoU6w0KoEFDx+1BxufOBjXVnmoFi5ZzYBYyI4Hb6xHXG7wUIA7vu05WTg2FXMggN1uR5Jlo6FsgVIxoLS1gLECZVe8A8TbjB3MhXd1Cxmhbr2BCFEAB+gddLezbnNlLqV85quvkktCVtT1kiWpDfkp0kxNgTeRqssMa0uXeJdGNYeW8KZOtdYqohx82+SIqMS77+oZl+jGgz/lwnY+MGuDbRmagyLp3HGnWgM/fX478RkwMyR0tkHQ5pNIhg4Z5tDMgGW5/Mc8lDeApDiC6ocl8OvTDOggkuwdgu2YXsc6lrq11daGohN5+8kdbhxHLO18SaM2x2zhoP8iUFxt1qcOf0F3oAIbPNUCVFI276Svx22PgQCN9/CWagndszdyLe7jNbTTB3ELvPcnwXYiYs=
