services:
  - postgresql
before_script:
  - bundle install
  # - cp config/database.yml.travis config/database.yml
  - psql -c 'create database pgapp_test;' -U postgres
  - bin/rails db:migrate
dist: trusty
language: ruby
rvm:
  - 2.6.5
script:
  - bundle exec rspec
deploy:
  provider: heroku
  api_key:
    secure: "f8KVMqFppLX4OaZc3s0B6rbrSy/gccv9G3s2rCW+mfodak+7nTH6E0+LcAbCUW+duxnVaeto2BY1MALuHSx4MA6bvG5Xwqah4kNFHXZS8EqyOsZtXXJuzIEAU0LYTIwDgM5VsGJdFz5GIK2pUvhbjQ24x8c/uI56kIifACE60BIMBZ53/FTnEiNCtqh/QG0xNTAh8iFpVKAd+C/npbXb936MAeApMRoVqKKqQcQUYKc30XBo65PGg17SrFVm6e0oyOuGV4DS2RYYeoQmqAhdLiPOTbKESw2wG29/TN5W3PWD7tQvmpSivNb5duZ2/LrXuGsEVcUPhQR0NOdfh0GzDuRroQDoZCbL5bdQDxeNd6Rhb6ZvoG42fb8TRA9S+/JUeu9st9EYceRtzS2hGXcK7SpoxioscxmMIcR4CjN/lVDWifPoUFIyfxCs4gBqT2G7DKZO58sjcTsZ7xiXrjU3rggpM8lXs6VVAPCi4ARXuSbeNxuLYia2CgGYxhW+SgifzzyFH6L+7GSO6bOMdP/m79CTcDK7qo3/T2fYkWoL1wGC242JAZ8MWQPDscSFbkn+WjgmbVkmCs26niJKqNu0mlt+8rs3BO/DJ76lTJq1s4QP0PE/noGl5B8JB5DC6VhQOPjlSz7iKbvahn+bncYntVJxHTkbqSYsOIyACM2EJEQ="



